pipeline {
    agent any
    stages{
        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }
        stage("Build"){
            steps{
                dir("Java_Clock"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("Java_Clock"){
                    sh "mvn test"
                }
            }
        }
    }
}