pipeline {
    agent any
tools {
    dockerTool 'docker-latest'
}

    stages{
        stage("Docker Build"){
            steps{
                sh "pwd"
                sh "ls -al"
                sh "docker build -t clock-image:${env.BUILD_NUMBER} ."
            }
        }
        stage("Build"){
            steps{
                withMaven(maven: 'Maven 3.8.6'){
                sh "mvn clean package"
                }
            }
        }
        stage("Test"){
            steps{
                sh "mvn test"
                }
        }
        
    }
}