pipeline {
    agent any
    stages{
        stage("Build"){
            steps{
                sh "mvn clean package"
                }
        }
        stage("Test"){
            steps{
                sh "mvn test"
                }
        }
        stage("Docker Build"){
            steps{
                sh "docker build -t clock-image:${env.BUILD_NUMBER} -f /Dockerfile ."
            }
        }
    }
}